# config/sources.yaml

version: 1.2.0

# Optional embed colors (Discord decimal RGB)
colors:
  default:       15844367   # light purple
  vpn:            3447003   # dark blue
  cloud_storage: 15844367   # light purple
  secure_email:   8311585   # teal
  proxy:         16776960   # yellow
  notes:         1146986    # green
  ai_tools:      16711935   # magenta
  dev_tools:      3066993   # blue-green
  certification: 15105570   # orange
  learning:       8636777   # indigo
  security_labs: 10038562   # red-brown

reddit:
  - vpndeals
  - vpncoupons
  - PrivacyDeals
  - softwaresale
  - Promocode
  - CouponCodes
  - SoftwareDeals
  - Freebies
  - Deals
  - BlackFridayDeals
  - Giveaways
  - FreeApps
  - ProductivityDeals
  - CyberDeals
  - PrivacyToolsIO
  - SecuritySoftware
  - EncryptionDeals
  - Proxies
  - CloudStorageDeals

html:
  - name: GrabOn VPN
    url: https://www.grabon.in/vpn-coupons/
    selector: .offer-box

  - name: WinningPC pCloud
    url: https://winningpc.com/pcloud-premium-giveaway-promo-codes/
    selector: h2

  - name: ProtonMail coupons
    url: https://protonmail.worthepenny.com/coupon/
    selector: tr

  - name: VPNMentor coupons
    url: https://www.vpnmentor.com/blog/vpn-coupons/
    selector: article .offer

  - name: Internxt coupons
    url: https://internxt.com/coupons/
    selector: .coupon-card

  # …and all your other html sources, each entry indented exactly like above…

rss:
  - name: Hugging Face RSS
    url: https://huggingface.co/feed
    selector: entry

  - name: PaperswithCode RSS
    url: https://paperswithcode.com/rss
    selector: item

  - name: Arxiv cs.CL RSS
    url: https://export.arxiv.org/rss/cs.CL
    selector: item

  # …and all your other rss sources…