# Global settings
global_min_hot: 0.05  # Reduced threshold
ttl_default_days: 30

# Optional embed colors (Discord decimal RGB)
colors:
  default:       15844367   # light purple
  vpn:            3447003   # dark blue
  cloud_storage: 15844367   # light purple
  secure_email:   8311585   # teal
  proxy:         16776960   # yellow
  notes:         1146986    # green
  ai_tools:      16711935   # magenta
  dev_tools:      3066993   # blue-green
  certification: 15105570   # orange
  learning:       8636777   # indigo
  security_labs: 10038562   # red-brown

# RSS Feeds
rss:
  - name: "Arxiv CS Updates"
    url: "https://export.arxiv.org/rss/cs.CL"
    tags: ["ai", "research"]
    min_hot_score: 0.05
    ttl_days: 1  # Check more frequently

  - name: "Papers with Code"
    url: "https://paperswithcode.com/rss"
    tags: ["ai", "code"]
    min_hot_score: 0.05
    ttl_days: 1

# HTML sources
html:
  - name: GrabOn VPN
    url: https://www.grabon.in/vpn-coupons/
    selector: .offer-box
    tags: ["vpn"]

  - name: WinningPC pCloud
    url: https://winningpc.com/pcloud-premium-giveaway-promo-codes/
    selector: h2
    tags: ["cloud"]

# Categories for Reddit
categories:
  privacy:
    reddit:
      - vpndeals
      - PrivacyDeals
      - PrivacyToolsIO
  
  software:
    reddit:
      - softwaresale
      - SoftwareDeals
      - FreeApps
      - ProductivityDeals

  deals:
    reddit:
      - Deals
      - BlackFridayDeals
      - CyberDeals
